#!/usr/bin/env bash
# =============================================================================
# setup_database.sh — Create the PostgreSQL database, user, and extensions.
# Extensions (pgvector, pg_trgm, uuid-ossp) require superuser privileges so
# they are created here. Django's migrate command handles all table creation.
#
# Usage:
#   chmod +x setup_database.sh
#   ./setup_database.sh
# =============================================================================

set -euo pipefail

DB_NAME="${DB_NAME:-preprint_bot}"
DB_USER="${DB_USER:-preprint_user}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
PG_SUPERUSER="${PG_SUPERUSER:-postgres}"

echo "============================================"
echo "  Preprint Bot — Database Setup"
echo "============================================"
echo ""

read -rp "Database name     [${DB_NAME}]: " input && DB_NAME="${input:-$DB_NAME}"
read -rp "Database user     [${DB_USER}]: " input && DB_USER="${input:-$DB_USER}"
read -rsp "Database password (hidden): " DB_PASSWORD && echo ""
read -rp "PostgreSQL host   [${DB_HOST}]: " input && DB_HOST="${input:-$DB_HOST}"
read -rp "PostgreSQL port   [${DB_PORT}]: " input && DB_PORT="${input:-$DB_PORT}"
read -rp "PG superuser      [${PG_SUPERUSER}]: " input && PG_SUPERUSER="${input:-$PG_SUPERUSER}"

echo ""

run_psql_super() {
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$PG_SUPERUSER" "$@"
}

# ── 1. Create the role ──────────────────────────────────────────────────
echo "[1/4] Creating role '${DB_USER}'..."
run_psql_super -tc \
    "SELECT 1 FROM pg_roles WHERE rolname = '${DB_USER}';" | grep -q 1 \
    && echo "      Role already exists, skipping." \
    || run_psql_super -c "CREATE ROLE ${DB_USER} WITH LOGIN PASSWORD '${DB_PASSWORD}';"

# ── 2. Create the database ──────────────────────────────────────────────
echo "[2/4] Creating database '${DB_NAME}'..."
run_psql_super -tc \
    "SELECT 1 FROM pg_database WHERE datname = '${DB_NAME}';" | grep -q 1 \
    && echo "      Database already exists, skipping." \
    || run_psql_super -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

run_psql_super -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
# The app user needs CREATE on the public schema for Django migrations
run_psql_super -d "$DB_NAME" -c "GRANT CREATE ON SCHEMA public TO ${DB_USER};"

# ── 3. Create extensions (requires superuser) ───────────────────────────
echo "[3/4] Creating PostgreSQL extensions (requires superuser)..."
run_psql_super -d "$DB_NAME" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
run_psql_super -d "$DB_NAME" -c 'CREATE EXTENSION IF NOT EXISTS vector;'
run_psql_super -d "$DB_NAME" -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'

# ── 4. Write .env ───────────────────────────────────────────────────────
ENV_DIR="${ENV_DIR:-django_site}"
ENV_FILE="${ENV_DIR}/.env"

echo "[4/4] Writing ${ENV_FILE}..."
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup_database.sh on $(date +%Y-%m-%d)
DATABASE_HOST=${DB_HOST}
DATABASE_PORT=${DB_PORT}
DATABASE_NAME=${DB_NAME}
DATABASE_USER=${DB_USER}
DATABASE_PASSWORD=${DB_PASSWORD}

DJANGO_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))" 2>/dev/null || echo "change-me-$(date +%s)")
DJANGO_DEBUG=True
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

API_BASE_URL=http://127.0.0.1:8000
SYSTEM_USER_EMAIL=ospo@syr.edu
EOF

echo ""
echo "============================================"
echo "  Database ready!"
echo "============================================"
echo ""
echo "  Next steps:"
echo "    cd django_site"
echo "    pip install -r requirements.txt"
echo "    python manage.py migrate"
echo "    python manage.py createsuperuser"
echo "    python manage.py runserver"
echo ""
