# Generated by Django 5.2.13 on 2026-04-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paper_sha256_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='corpus',
            field=models.ForeignKey(blank=True, help_text='Deprecated — not populated. Use corpora M2M. Can be dropped in a future migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers_legacy', to='core.corpus'),
        ),
        migrations.AlterField(
            model_name='pbuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('paper', 'type', 'model_name'), name='embeddings_paper_type_model_null_section_unique'),
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', False)), fields=('paper', 'section', 'type', 'model_name'), name='embeddings_paper_section_type_model_unique'),
        ),
    ]
