# Generated by Django 5.2.13 on 2026-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paper_corpus_alter_pbuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
    ]
